<h2>Toronto and New York Restaurants Comparison</h2>

<h4>Opening a restaurant is one of the most important financial decisions an individual will make in their lifetime. It can be a daunting experience for some.</h4>

<h4>Throughout project, I explore the in-depth process of opening a restaurant in New York and Toronto. Where the processes diverge between the two cities, I explain the differences. It’s our goal to educate potential restaurant owner about the differences and make it easier to understand. </h4>

<h4>New York and Toronto are two of biggest cities in North East. New York is famously diverse city. New York City welcomed a record 65.2 million visitors, comprising 51.6 million domestic and 13.5 million international visitors, the ninth consecutive year of tourism growth<h/4>

<h4>Long recognized as one of the most livable cities in the world, Toronto has only recently started receiving the attention it deserves as a tourist destination, and there’s never been a better time to visit. Urban renewal projects have transformed industrial zones, and an energetic dining scene churns out a steady stream of innovative restaurants.</h4>

<h3>For this project we need the following data :</h3>

</h4>Wikipedia page of New York City ant Toronto neighborhood data that including contains list Boroughs, Neighborhoods along with their latitude and longitude. Data source : https://cocl.us/new_york_dataset<h4>

<h4>Nearby venues for each neighborhood in the cities through Foursqueare API Data source : Fousquare API Description : By using this api we will get all the venues in each neighborhood.</h4>

<h4>Nearby venues for each neighborhood in the cities through Foursqueare API Data source : Fousquare API</h4>

<h3>Approach</h3>

<h4>Collect the new york city data from https://cocl.us/new_york_dataset</h4>

<h4>Using FourSquare API we will find all venues for each neighborhood. Filter out all venues. Find rating, tips and like count for Restaurants. Using rating for each restaurant sort that data</h4>

<h4>Clustering medit going to be used<h/4>

<h4>Visualize the Ranking of neighborhoods using folium library</h4>

<h3>Analysis</h3>

<h4>Import the required libraries for python: Pandas, numpy, and Sklearn</h4>

<h4>Geopy to get co-ordinates of New York and Toronto</4>

<h4>Folium to visualize the results on a map</h4>

<h2>Toronto Restaurants Analysys<h/2>

In [ ]:
import requests
import pandas as pd
import numpy as np
import json
from pandas.io.json import json_normalize
# import k-means from clustering stage
from sklearn.cluster import KMeans
import matplotlib.cm as cm
import matplotlib.colors as colors
#!conda install -c conda-forge folium=0.5.0 --yes # uncomment this line if you haven't completed the Foursquare API lab
import folium # map rendering library

In [ ]:
<h2>Configuring the foursquare credentials</h2

In [10]:
website_url = requests.get("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M").text
!conda install -c conda-forge beautifulsoup4 --yes

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.7.12

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

In [11]:
!conda install -c conda-forge lxml --yes
from bs4 import BeautifulSoup
soup = BeautifulSoup(website_url,"html5lib")

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.7.12

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

In [13]:
My_table = soup.find("table",{"class":"wikitable sortable"})
x=My_table.find_all('td')

In [14]:
counter=0
a=[]
b=[]
c=[]
for i in x:
    v=i.next
    if counter==0:
        a.append(v)
        counter+=1
        continue
    if counter==1:
        b.append(v)
        counter+=1
        continue
    if counter==2:
        c.append(v)
        counter=0

In [15]:
borough=[]
counter=0
for i in b:
    
    if str(i)!="Not assigned" and str(i)!="York" and str(i)!="Mississauga" :
        counter+=1
        x=str(i).index("title=")+7
        y=str(i).index('">')
        borough.append(str(i)[x:y])
    elif "Scarborough" in str(i):
        borough.append("Scarborough")
    else:
        borough.append(str(i))
        
borough=[i.replace("Scarborough, Toronto","Scarborough") for i in borough]
borough=[i.replace(",Toronto"," Toronto") for i in borough]
borough
print(borough)

['Not assigned', 'Not assigned', 'North York', 'North York', 'Downtown Toronto', 'North York', 'North York', "Queen's Park (Toronto)", 'Not assigned', 'Downtown Toronto', 'Scarborough', 'Scarborough', 'Not assigned', 'North York', 'East York', 'East York', 'Downtown Toronto', 'Downtown Toronto', 'North York', 'Not assigned', 'Not assigned', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Scarborough', 'Scarborough', 'Scarborough', 'Not assigned', 'North York', 'North York', 'East York', 'Downtown Toronto', 'York', 'Not assigned', 'Not assigned', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Scarborough', 'Scarborough', 'Scarborough', 'Not assigned', 'Not assigned', 'East Toronto', 'Downtown Toronto', 'York', 'Not assigned', 'Not assigned', 'Not assigned', 'Scarborough', 'Not assigned', 'Not assigned', 'East York', 'Downtown Toronto', 'Downtown Toronto', 'Not assigned', 'Not assigned', 'Not assigned', 'Scarborough', 'North York', 'North York', 'North York', 'North York', 'East York', 'Downtown Toronto', 'Downtown Toronto', 'Downtown Toronto', 'West Toronto', 'West Toronto', 'Not assigned', 'Not assigned', 'Not assigned', 'Scarborough', 'North York', 'North York', 'North York', 'North York', 'North York', 'East York', 'Downtown Toronto', 'Downtown Toronto', 'Downtown Toronto', 'West Toronto', 'West Toronto', 'Not assigned', 'Not assigned', 'Not assigned', 'Scarborough', 'Scarborough', 'Scarborough', 'North York', 'North York', 'North York', 'East Toronto', 'East Toronto', 'Downtown Toronto', 'Downtown Toronto', 'West Toronto', 'West Toronto', 'West Toronto', 'Not assigned', 'Not assigned', 'Not assigned', 'Scarborough', 'Scarborough', 'Scarborough', 'North York', 'North York', 'North York', 'East Toronto', 'East Toronto', 'Downtown Toronto', 'Downtown Toronto', 'North York', 'North York', 'North York', 'Not assigned', 'Not assigned', 'North York', 'Scarborough', 'Scarborough', 'Scarborough', 'North York', 'North York', 'North York', 'East Toronto', 'North York', 'North York', 'York, Toronto', 'York, Toronto', 'York, Toronto', 'York, Toronto', 'Not assigned', 'Not assigned', 'North York', 'North York', 'Scarborough', 'Scarborough', 'North York', 'North York', 'Central Toronto', 'Central Toronto', 'York, Toronto', 'York, Toronto', 'Not assigned', 'Not assigned', 'York, Toronto', 'Scarborough', 'Scarborough', 'Scarborough', 'North York', 'Not assigned', 'Central Toronto', 'Central Toronto', 'Central Toronto', 'West Toronto', 'West Toronto', 'Not assigned', 'Not assigned', 'Etobicoke', 'Scarborough', 'Scarborough', 'North York', 'Not assigned', 'Central Toronto', 'Central Toronto', 'Central Toronto', 'Central Toronto', 'West Toronto', 'West Toronto', 'Mississauga', 'Not assigned', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Scarborough', 'Not assigned', 'Not assigned', 'Central Toronto', 'Downtown Toronto', 'Downtown Toronto', 'West Toronto', 'West Toronto', 'Not assigned', 'Not assigned', 'Not assigned', 'Scarborough', 'Scarborough', 'Scarborough', 'Not assigned', 'Not assigned', 'Central Toronto', 'Central Toronto', 'Downtown Toronto', 'Downtown Toronto', 'Downtown Toronto', 'Not assigned', 'Not assigned', 'Not assigned', 'Not assigned', 'Scarborough', 'Scarborough', 'Scarborough', 'Scarborough', 'Not assigned', 'Not assigned', 'Central Toronto', 'Central Toronto', 'Central Toronto', 'Central Toronto', 'Central Toronto', 'Downtown Toronto', 'Downtown Toronto', 'Downtown Toronto', 'Downtown Toronto', 'Downtown Toronto', 'Downtown Toronto', 'Downtown Toronto', 'Not assigned', 'Not assigned', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Scarborough', 'Not assigned', 'Not assigned', 'Downtown Toronto', 'Downtown Toronto', 'Not assigned', 'Not assigned', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Scarborough', 'Not assigned', 'Not assigned', 'Downtown Toronto', 'Downtown Toronto', 'Downtown Toronto', 'Downtown Toronto', 'Not assigned', 'Not assigned', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Not assigned', 'Not assigned', 'Not assigned', 'Not assigned', 'Downtown Toronto', 'Not assigned', 'Not assigned', 'East Toronto', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Not assigned', 'Not assigned', 'Not assigned', 'Not assigned', 'Not assigned', 'Not assigned', 'Not assigned', 'Not assigned', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Etobicoke', 'Not assigned']

In [16]:
postcode=[]
for i in a:
    postcode.append(str(i))
    
print(postcode)

['M1A', 'M2A', 'M3A', 'M4A', 'M5A', 'M6A', 'M6A', 'M7A', 'M8A', 'M9A', 'M1B', 'M1B', 'M2B', 'M3B', 'M4B', 'M4B', 'M5B', 'M5B', 'M6B', 'M7B', 'M8B', 'M9B', 'M9B', 'M9B', 'M9B', 'M9B', 'M1C', 'M1C', 'M1C', 'M2C', 'M3C', 'M3C', 'M4C', 'M5C', 'M6C', 'M7C', 'M8C', 'M9C', 'M9C', 'M9C', 'M9C', 'M1E', 'M1E', 'M1E', 'M2E', 'M3E', 'M4E', 'M5E', 'M6E', 'M7E', 'M8E', 'M9E', 'M1G', 'M2G', 'M3G', 'M4G', 'M5G', 'M6G', 'M7G', 'M8G', 'M9G', 'M1H', 'M2H', 'M3H', 'M3H', 'M3H', 'M4H', 'M5H', 'M5H', 'M5H', 'M6H', 'M6H', 'M7H', 'M8H', 'M9H', 'M1J', 'M2J', 'M2J', 'M2J', 'M3J', 'M3J', 'M4J', 'M5J', 'M5J', 'M5J', 'M6J', 'M6J', 'M7J', 'M8J', 'M9J', 'M1K', 'M1K', 'M1K', 'M2K', 'M3K', 'M3K', 'M4K', 'M4K', 'M5K', 'M5K', 'M6K', 'M6K', 'M6K', 'M7K', 'M8K', 'M9K', 'M1L', 'M1L', 'M1L', 'M2L', 'M2L', 'M3L', 'M4L', 'M4L', 'M5L', 'M5L', 'M6L', 'M6L', 'M6L', 'M7L', 'M8L', 'M9L', 'M1M', 'M1M', 'M1M', 'M2M', 'M2M', 'M3M', 'M4M', 'M5M', 'M5M', 'M6M', 'M6M', 'M6M', 'M6M', 'M7M', 'M8M', 'M9M', 'M9M', 'M1N', 'M1N', 'M2N', 'M3N', 'M4N', 'M5N', 'M6N', 'M6N', 'M7N', 'M8N', 'M9N', 'M1P', 'M1P', 'M1P', 'M2P', 'M3P', 'M4P', 'M5P', 'M5P', 'M6P', 'M6P', 'M7P', 'M8P', 'M9P', 'M1R', 'M1R', 'M2R', 'M3R', 'M4R', 'M5R', 'M5R', 'M5R', 'M6R', 'M6R', 'M7R', 'M8R', 'M9R', 'M9R', 'M9R', 'M9R', 'M1S', 'M2S', 'M3S', 'M4S', 'M5S', 'M5S', 'M6S', 'M6S', 'M7S', 'M8S', 'M9S', 'M1T', 'M1T', 'M1T', 'M2T', 'M3T', 'M4T', 'M4T', 'M5T', 'M5T', 'M5T', 'M6T', 'M7T', 'M8T', 'M9T', 'M1V', 'M1V', 'M1V', 'M1V', 'M2V', 'M3V', 'M4V', 'M4V', 'M4V', 'M4V', 'M4V', 'M5V', 'M5V', 'M5V', 'M5V', 'M5V', 'M5V', 'M5V', 'M6V', 'M7V', 'M8V', 'M8V', 'M8V', 'M9V', 'M9V', 'M9V', 'M9V', 'M9V', 'M9V', 'M9V', 'M9V', 'M1W', 'M2W', 'M3W', 'M4W', 'M5W', 'M6W', 'M7W', 'M8W', 'M8W', 'M9W', 'M1X', 'M2X', 'M3X', 'M4X', 'M4X', 'M5X', 'M5X', 'M6X', 'M7X', 'M8X', 'M8X', 'M8X', 'M9X', 'M1Y', 'M2Y', 'M3Y', 'M4Y', 'M5Y', 'M6Y', 'M7Y', 'M8Y', 'M8Y', 'M8Y', 'M8Y', 'M8Y', 'M8Y', 'M8Y', 'M8Y', 'M9Y', 'M1Z', 'M2Z', 'M3Z', 'M4Z', 'M5Z', 'M6Z', 'M7Z', 'M8Z', 'M8Z', 'M8Z', 'M8Z', 'M8Z', 'M9Z']

In [17]:
neighbourhood=[]
counter=0
for i in c:
    if "</a>"not in str(i):
        neighbourhood.append(str(i))
    else:
        counter+=1
        x=str(i).index("title=")+7
        y=str(i).index('">')
        neighbourhood.append(str(i)[x:y])
        
neighbourhood = [i.replace("\n", "") for i in neighbourhood]   
print(neighbourhood)

['Not assigned', 'Not assigned', 'Parkwoods', 'Victoria Village', 'Regent Park', 'Lawrence Heights', 'Lawrence Manor', 'Not assigned', 'Not assigned', "Queen's Park (Toronto)", 'Rouge, Toronto', 'Malvern, Toronto', 'Not assigned', 'Don Mills North', 'Woodbine Gardens', 'Parkview Hill', 'Ryerson', 'Garden District', 'Glencairn', 'Not assigned', 'Not assigned', 'Cloverdale', 'Islington, Toronto', 'Martin Grove', 'Princess Gardens', 'West Deane Park', 'Highland Creek (Toronto)', 'Rouge Hill', 'Port Union, Toronto', 'Not assigned', 'Flemingdon Park', 'Don Mills South', 'Woodbine Heights', 'St. James Town', 'Humewood-Cedarvale', 'Not assigned', 'Not assigned', 'Bloordale Gardens', 'Eringate', 'Markland Wood', 'Old Burnhamthorpe', 'Guildwood', 'Morningside, Toronto', 'West Hill, Toronto', 'Not assigned', 'Not assigned', 'The Beaches', 'Berczy Park', 'Caledonia-Fairbanks', 'Not assigned', 'Not assigned', 'Not assigned', 'Woburn, Toronto', 'Not assigned', 'Not assigned', 'Leaside', 'Central Bay Street', 'Christie', 'Not assigned', 'Not assigned', 'Not assigned', 'Cedarbrae', 'Hillcrest Village', 'Bathurst Manor', 'Downsview North', 'Wilson Heights, Toronto', 'Thorncliffe Park', 'Adelaide', 'King', 'Richmond', 'Dovercourt Village', 'Dufferin', 'Not assigned', 'Not assigned', 'Not assigned', 'Scarborough Village', 'Fairview', 'Henry Farm', 'Oriole', 'Northwood Park', 'York University', 'East Toronto', 'Harbourfront East', 'Toronto Islands', 'Union Station (Toronto)', 'Little Portugal, Toronto', 'Trinity–Bellwoods', 'Not assigned', 'Not assigned', 'Not assigned', 'East Birchmount Park', 'Ionview', 'Kennedy Park, Toronto', 'Bayview Village', 'CFB Toronto', 'Downsview East', 'The Danforth West', 'Riverdale, Toronto', 'Design Exchange', 'Toronto Dominion Centre', 'Brockton', 'Exhibition Place', 'Parkdale Village', 'Not assigned', 'Not assigned', 'Not assigned', 'Clairlea', 'Golden Mile, Toronto', 'Oakridge, Toronto', 'Silver Hills', 'York Mills', 'Downsview', 'The Beaches West', 'India Bazaar', 'Commerce Court', 'Victoria Hotel', 'Downsview, Toronto', 'North Park', 'Upwood Park', 'Not assigned', 'Not assigned', 'Humber Summit', 'Cliffcrest', 'Cliffside, Toronto', 'Scarborough Village West', 'Newtonbrook', 'Willowdale, Toronto', 'Downsview Central', 'Studio District', 'Bedford Park, Toronto', 'Lawrence Manor East', 'Del Ray', 'Keelesdale', 'Mount Dennis', 'Silverthorn, Toronto', 'Not assigned', 'Not assigned', 'Emery, Toronto', 'Humberlea', 'Birch Cliff', 'Cliffside West', 'Willowdale South', 'Downsview Northwest', 'Lawrence Park, Toronto', 'Roselawn', 'The Junction North', 'Runnymede', 'Not assigned', 'Not assigned', 'Weston, Toronto', 'Dorset Park', 'Scarborough Town Centre', 'Wexford Heights', 'York Mills West', 'Not assigned', 'Davisville North', 'Forest Hill North', 'Forest Hill West', 'High Park', 'The Junction South', 'Not assigned', 'Not assigned', 'Westmount', 'Maryvale, Toronto', 'Wexford, Toronto', 'Willowdale West', 'Not assigned', 'North Toronto West', 'The Annex', 'North Midtown', 'Yorkville, Toronto', 'Parkdale, Toronto', 'Roncesvalles, Toronto', 'Canada Post Gateway Processing Centre', 'Not assigned', 'Kingsview Village', 'Martin Grove Gardens', 'Richview Gardens', 'St. Phillips', 'Agincourt, Toronto', 'Not assigned', 'Not assigned', 'Davisville', 'Harbord', 'University of Toronto', 'Runnymede, Toronto', 'Swansea, Toronto', 'Not assigned', 'Not assigned', 'Not assigned', 'Clarks Corners', 'Sullivan', "Tam O'Shanter – Sullivan", 'Not assigned', 'Not assigned', 'Moore Park, Toronto', 'Summerhill East', 'Chinatown, Toronto', 'Grange Park (Toronto)', 'Kensington Market', 'Not assigned', 'Not assigned', 'Not assigned', 'Not assigned', 'Agincourt North', "L'Amoreaux East", 'Milliken, Ontario', 'Steeles East', 'Not assigned', 'Not assigned', 'Deer Park, Toronto', 'Forest Hill SE', 'Rathnelly', 'South Hill, Toronto', 'Summerhill West', 'CN Tower', 'Bathurst Quay', 'Island airport', 'Harbourfront West', 'King and Spadina', 'Railway Lands', 'South Niagara', 'Not assigned', 'Not assigned', 'Humber Bay Shores', 'Mimico South', 'New Toronto', 'Albion Gardens', 'Beaumond Heights', 'Humbergate', 'Mount Olive-Silverstone-Jamestown', 'Mount Olive-Silverstone-Jamestown', 'Silverstone, Toronto', 'South Steeles', 'Thistletown', "L'Amoreaux West", 'Not assigned', 'Not assigned', 'Rosedale, Toronto', 'Stn A PO Boxes 25 The Esplanade', 'Not assigned', 'Not assigned', 'Alderwood, Toronto', 'Long Branch, Toronto', 'Northwest', 'Upper Rouge', 'Not assigned', 'Not assigned', 'Cabbagetown, Toronto', 'St. James Town', 'First Canadian Place', 'Underground city', 'Not assigned', 'Not assigned', 'The Kingsway', 'Montgomery Road', 'Old Mill North', 'Not assigned', 'Not assigned', 'Not assigned', 'Not assigned', 'Church and Wellesley', 'Not assigned', 'Not assigned', 'Business Reply Mail Processing Centre 969 Eastern', 'Humber Bay', "King's Mill Park", 'Kingsway Park South East', 'Mimico', 'Old Mill, Toronto', 'The Queensway', 'Fairmont Royal York Hotel', 'Sunnylea', 'Not assigned', 'Not assigned', 'Not assigned', 'Not assigned', 'Not assigned', 'Not assigned', 'Not assigned', 'Not assigned', 'Kingsway Park South West', 'Mimico', 'The Queensway', 'Royal York South West', 'South of Bloor', 'Not assigned']

In [18]:
df=pd.DataFrame()
df["postcode"]=postcode
df["borough"]=borough
df["neighbourhood"]=neighbourhood
df.head(10)

  postcode                 borough           neighbourhood
0      M1A            Not assigned            Not assigned
1      M2A            Not assigned            Not assigned
2      M3A              North York               Parkwoods
3      M4A              North York        Victoria Village
4      M5A        Downtown Toronto             Regent Park
5      M6A              North York        Lawrence Heights
6      M6A              North York          Lawrence Manor
7      M7A  Queen's Park (Toronto)            Not assigned
8      M8A            Not assigned            Not assigned
9      M9A        Downtown Toronto  Queen's Park (Toronto)

In [19]:
df = df[df.borough != "Not assigned"]

for i,v in df.iterrows():
    if v["neighbourhood"]=="Not assigned":
        v["neighbourhood"]=v["borough"]
df_toronto=df[df['borough'].str.contains("Toronto")]
df_toronto

,postcode,borough,neighbourhood
4,M5A,Downtown Toronto,Regent Park
7,M7A,Queen's Park (Toronto),Queen's Park (Toronto)
9,M9A,Downtown Toronto,Queen's Park (Toronto)
16,M5B,Downtown Toronto,Ryerson
17,M5B,Downtown Toronto,Garden District
...,...,...,...
249,M4X,Downtown Toronto,St. James Town
250,M5X,Downtown Toronto,First Canadian Place
251,M5X,Downtown Toronto,Underground city
261,M4Y,Downtown Toronto,Church and Wellesley
264,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern

In [22]:
df2=pd.read_csv("http://cocl.us/Geospatial_data")
df2.rename(columns={"Postal Code":"postcode"},inplace=True)
df3=pd.merge(df_toronto, df2, on="postcode", how='inner')
df3.head(10)

,postcode,borough,neighbourhood,Latitude,Longitude
0,M5A,Downtown Toronto,Regent Park,43.654260,-79.360636
1,M7A,Queen's Park (Toronto),Queen's Park (Toronto),43.662301,-79.389494
2,M9A,Downtown Toronto,Queen's Park (Toronto),43.667856,-79.532242
3,M5B,Downtown Toronto,Ryerson,43.657162,-79.378937
4,M5B,Downtown Toronto,Garden District,43.657162,-79.378937
5,M5C,Downtown Toronto,St. James Town,43.651494,-79.375418
6,M4E,East Toronto,The Beaches,43.676357,-79.293031
7,M5E,Downtown Toronto,Berczy Park,43.644771,-79.373306
8,M5G,Downtown Toronto,Central Bay Street,43.657952,-79.387383
9,M6G,Downtown Toronto,Christie,43.669542,-79.422564

In [23]:
CLIENT_ID = "FWA1UIVYVSYB3NX0ZDZDT02CKWNXXS3C2VHZEDTGUX4T0FVY" # your Foursquare ID
CLIENT_SECRET = "RQBPPI3SQJU5RPF5RKFTSPK21Q5DILZQF4H15MH4R3R4ZQCE" # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: FWA1UIVYVSYB3NX0ZDZDT02CKWNXXS3C2VHZEDTGUX4T0FVY
CLIENT_SECRET:RQBPPI3SQJU5RPF5RKFTSPK21Q5DILZQF4H15MH4R3R4ZQCE

In [24]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        #print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            500, 
            100)
            
        # make the GET request
        #print(requests.get(url).json())
        group_data = requests.get(url).json().get("response").get('groups')
        
        if group_data:
            results = group_data[0].get('items')
        else:
            results=''
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v.get("venue").get("id"),
            v.get('venue').get('name'), 
            v.get('venue').get('location').get('lat'), 
            v.get('venue').get('location').get('lng'),  
            v.get('venue').get('categories')[0].get('name')) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue ID',
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [26]:
toronto_venues = getNearbyVenues(names=df3['neighbourhood'],
                                   latitudes=df3['Latitude'],
                                   longitudes=df3['Longitude']
                                  )
print(toronto_venues.shape)

print(np.unique(toronto_venues["Venue Category"],return_counts=True))

(3215, 8)
(array(['Afghan Restaurant', 'Airport', 'Airport Food Court',
       'Airport Gate', 'Airport Lounge', 'Airport Service',
       'Airport Terminal', 'American Restaurant', 'Antique Shop',
       'Aquarium', 'Argentinian Restaurant', 'Art Gallery',
       'Arts & Crafts Store', 'Asian Restaurant', 'Athletics & Sports',
       'Auto Workshop', 'BBQ Joint', 'Baby Store', 'Bagel Shop', 'Bakery',
       'Bank', 'Bar', 'Baseball Stadium', 'Basketball Stadium',
       'Bed & Breakfast', 'Beer Bar', 'Beer Store', 'Belgian Restaurant',
       'Bistro', 'Board Shop', 'Boat or Ferry', 'Bookstore', 'Boutique',
       'Brazilian Restaurant', 'Breakfast Spot', 'Brewery',
       'Bubble Tea Shop', 'Building', 'Burger Joint', 'Burrito Place',
       'Bus Line', 'Butcher', 'Café', 'Cajun / Creole Restaurant',
       'Camera Store', 'Candy Store', 'Caribbean Restaurant',
       'Cheese Shop', 'Chinese Restaurant', 'Chocolate Shop', 'Church',
       'Climbing Gym', 'Clothing Store', 'Cocktail Bar', 'Coffee Shop',
       'College Arts Building', 'College Auditorium', 'College Gym',
       'College Rec Center', 'Colombian Restaurant',
       'Comfort Food Restaurant', 'Comic Shop', 'Concert Hall',
       'Convenience Store', 'Cosmetics Shop', 'Costume Shop',
       'Coworking Space', 'Creperie', 'Cuban Restaurant', 'Cupcake Shop',
       'Dance Studio', 'Deli / Bodega', 'Department Store',
       'Dessert Shop', 'Dim Sum Restaurant', 'Diner', 'Discount Store',
       'Dog Run', 'Doner Restaurant', 'Donut Shop', 'Dumpling Restaurant',
       'Eastern European Restaurant', 'Electronics Store',
       'Ethiopian Restaurant', 'Event Space', 'Falafel Restaurant',
       'Farmers Market', 'Fast Food Restaurant', 'Festival',
       'Filipino Restaurant', 'Fish & Chips Shop', 'Fish Market',
       'Flea Market', 'Flower Shop', 'Food', 'Food & Drink Shop',
       'Food Court', 'Food Truck', 'Fountain', 'French Restaurant',
       'Fried Chicken Joint', 'Fruit & Vegetable Store',
       'Furniture / Home Store', 'Gaming Cafe', 'Garden', 'Garden Center',
       'Gastropub', 'Gay Bar', 'General Entertainment', 'General Travel',
       'German Restaurant', 'Gift Shop', 'Gluten-free Restaurant',
       'Gourmet Shop', 'Greek Restaurant', 'Grocery Store', 'Gym',
       'Gym / Fitness Center', 'Harbor / Marina',
       'Health & Beauty Service', 'Health Food Store', 'Historic Site',
       'History Museum', 'Hobby Shop', 'Hookah Bar', 'Hospital', 'Hostel',
       'Hotel', 'Hotel Bar', 'Hotpot Restaurant', 'IT Services',
       'Ice Cream Shop', 'Indian Restaurant', 'Indie Movie Theater',
       'Intersection', 'Irish Pub', 'Italian Restaurant',
       'Japanese Restaurant', 'Jazz Club', 'Jewelry Store', 'Juice Bar',
       'Korean Restaurant', 'Lake', 'Latin American Restaurant',
       'Light Rail Station', 'Lingerie Store', 'Liquor Store', 'Lounge',
       'Mac & Cheese Joint', 'Market', 'Massage Studio',
       'Mediterranean Restaurant', "Men's Store", 'Mexican Restaurant',
       'Middle Eastern Restaurant', 'Miscellaneous Shop',
       'Modern European Restaurant', 'Molecular Gastronomy Restaurant',
       'Monument / Landmark', 'Movie Theater', 'Museum', 'Music Venue',
       'Neighborhood', 'New American Restaurant', 'Nightclub',
       'Noodle House', 'Office', 'Opera House', 'Optical Shop',
       'Organic Grocery', 'Other Great Outdoors', 'Park',
       'Performing Arts Venue', 'Persian Restaurant', 'Pet Store',
       'Pharmacy', 'Pizza Place', 'Playground', 'Plaza', 'Poke Place',
       'Portuguese Restaurant', 'Poutine Place', 'Pub',
       'Ramen Restaurant', 'Record Shop', 'Recording Studio',
       'Rental Car Location', 'Restaurant', 'Roof Deck', 'Sake Bar',
       'Salad Place', 'Salon / Barbershop', 'Sandwich Place',
       'Scenic Lookout', 'Sculpture Garden', 'Seafood Restaurant',
       'Shoe Store', 'Shopping Mall', 'Skate Park', 'Skating Rink',
       'Smoke Shop', 'Smoothie Shop', 'Southern / Soul Food Restaurant',
       'Spa', 'Speakeasy', 'Sporting Goods Shop', 'Sports Bar', 'Stadium',
       'Stationery Store', 'Steakhouse', 'Strip Club', 'Supermarket',
       'Sushi Restaurant', 'Swim School', 'Taco Place', 'Tailor Shop',
       'Taiwanese Restaurant', 'Tanning Salon', 'Tea Room',
       'Thai Restaurant', 'Theater', 'Theme Restaurant',
       'Thrift / Vintage Store', 'Toy / Game Store', 'Trail',
       'Train Station', 'Vegetarian / Vegan Restaurant',
       'Video Game Store', 'Vietnamese Restaurant', 'Wine Bar',
       'Wings Joint', 'Yoga Studio'], dtype=object), array([  1,   7,   7,   7,  14,  14,  14,  47,   4,  15,   2,  22,   7,
        27,   1,   1,   6,   1,  10,  82,  11,  90,   6,   6,   3,  30,
         5,   3,   4,   2,   7,  32,   9,   5,  32,  26,  16,   7,  38,
        20,   3,   3, 172,   2,   1,   1,  13,   7,  24,   1,   2,   3,
        29,  16, 268,   2,   1,   2,   2,   3,  11,   4,  15,  10,  27,
         1,   1,   7,   4,   2,   4,  29,  11,  25,   3,  26,   6,   3,
         3,   7,  12,   2,   7,   3,   4,   3,  13,  16,   3,   3,   4,
         6,   2,   4,   2,   7,  17,   4,   4,  14,  26,   2,  16,   3,
         2,   1,  39,   5,   3,   9,   1,   8,   7,   7,  24,  22,  41,
        22,   7,   3,   4,   1,   9,   2,   2,   3,   2,  70,  12,   3,
         3,  28,  14,   2,   5,   3,  75,  43,   7,   4,  12,   6,   5,
         9,   6,   3,  18,  17,   2,   2,   3,   8,   8,  23,  11,   5,
         6,   1,   8,   8,   7,  13,   8,  17,   5,  10,   6,   5,   1,
         3,   3,  55,   7,   2,   9,  13,  61,   7,  15,   5,   2,   5,
        41,  12,  11,   1,   8, 107,   3,   1,  24,   8,  53,   9,   8,
        36,   3,  11,   1,   3,   9,  11,   2,  11,  13,  15,  11,   3,
         1,  40,   1,  12,  41,   1,   2,   6,   2,   2,  24,  36,  25,
         1,   3,   4,   6,   7,  38,   4,  24,  21,   2,  12]))

In [27]:
print('There are {} uniques categories.'.format(len(toronto_venues['Venue Category'].unique())))

There are 232 uniques categories.

<hh2>Unique categories of restaurants in Toronto</h2>

In [28]:
toronto_restaurants_array=np.unique(toronto_venues["Venue Category"].loc[toronto_venues["Venue Category"].str.contains("Restaurant")],return_counts=True)
print(len(toronto_restaurants_array[0]))
print(toronto_restaurants_array)

48
(array(['Afghan Restaurant', 'American Restaurant',
       'Argentinian Restaurant', 'Asian Restaurant', 'Belgian Restaurant',
       'Brazilian Restaurant', 'Cajun / Creole Restaurant',
       'Caribbean Restaurant', 'Chinese Restaurant',
       'Colombian Restaurant', 'Comfort Food Restaurant',
       'Cuban Restaurant', 'Dim Sum Restaurant', 'Doner Restaurant',
       'Dumpling Restaurant', 'Eastern European Restaurant',
       'Ethiopian Restaurant', 'Falafel Restaurant',
       'Fast Food Restaurant', 'Filipino Restaurant', 'French Restaurant',
       'German Restaurant', 'Gluten-free Restaurant', 'Greek Restaurant',
       'Hotpot Restaurant', 'Indian Restaurant', 'Italian Restaurant',
       'Japanese Restaurant', 'Korean Restaurant',
       'Latin American Restaurant', 'Mediterranean Restaurant',
       'Mexican Restaurant', 'Middle Eastern Restaurant',
       'Modern European Restaurant', 'Molecular Gastronomy Restaurant',
       'New American Restaurant', 'Persian Restaurant',
       'Portuguese Restaurant', 'Ramen Restaurant', 'Restaurant',
       'Seafood Restaurant', 'Southern / Soul Food Restaurant',
       'Sushi Restaurant', 'Taiwanese Restaurant', 'Thai Restaurant',
       'Theme Restaurant', 'Vegetarian / Vegan Restaurant',
       'Vietnamese Restaurant'], dtype=object), array([  1,  47,   2,  27,   3,   5,   2,  13,  24,   3,  11,   4,   3,
         3,  12,   2,   3,   3,  16,   3,  14,   1,   7,  24,   3,  14,
        75,  43,   6,   9,   8,  23,  11,   6,   1,  17,   2,   2,  12,
       107,  36,   2,  41,   2,  36,   1,  38,  24]))

In [29]:
print(toronto_venues.columns)

Index(['Neighborhood', 'Neighborhood Latitude', 'Neighborhood Longitude',
       'Venue ID', 'Venue', 'Venue Latitude', 'Venue Longitude',
       'Venue Category'],
      dtype='object')

<h2> Extract Data</h2>

In [30]:
toronto_rest_2=toronto_venues.loc[toronto_venues["Venue Category"].str.contains("Restaurant")]
toronto_rest_2=toronto_rest_2.loc[:,["Venue","Venue Latitude","Venue Longitude","Venue Category","Venue ID"]]
toronto_rest_2.head()

,Venue,Venue Latitude,Venue Longitude,Venue Category,Venue ID
5,Impact Kitchen,43.656369,-79.356980,Restaurant,5612b1cc498e3dd742af0dc8
19,El Catrin,43.650601,-79.358920,Mexican Restaurant,51ddecee498e1ffd34185d2f
20,Cocina Economica,43.654959,-79.365657,Mexican Restaurant,5542ab36498e2f92a8c248f2
24,Cluny Bistro & Boulangerie,43.650565,-79.357843,French Restaurant,53a22c92498ec91fda7ce133
25,Souvlaki Express,43.655584,-79.364438,Greek Restaurant,4bc39c914cdfc9b6f29c9721

<h2>Get price, likes count and rating for each restaurat</h2>

In [31]:
def getRestaurntDetails(names,IDs):
    
    details_list=[]
    for name,ID in zip(names,IDs):
        #print(name)
            
        # create the API request URL
        url="https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}".format(
            ID,
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION         )
            
        # make the GET request
        
        group_data = requests.get(url).json()
        
        #print(group_data)
         #break
        if group_data.get("response"):
        
            #print(group_data.get("response"))
        
            
            if group_data.get("response").get("venue"):
                if group_data.get("response").get("venue").get("price"):
                    if group_data.get("response").get("venue").get("price").get("message"):
                        
                            details_list.append([(name, 
                                                  group_data.get("response").get('venue').get("price").get("message"),
                                                  group_data.get("response").get('venue').get("rating"),
                                                  group_data.get("response").get('venue').get("likes").get("count")
                                                 ) ])
                            

    
    details = pd.DataFrame([item for detail_list in details_list for item in detail_list])
    #details.head()
    #print(details)
    details.columns = ['Rest_name', 
                       'Price', 
                       'Rating' ,
                       'Likes Count'
                      ]
    
    return(details)

In [32]:
toronto_rest_2.shape
toronto_rest_2_distinct=toronto_rest_2.drop_duplicates('Venue')
toronto_rest_3=toronto_rest_2_distinct.iloc[0:200,:]
toronto_rest_3

,Venue,Venue Latitude,Venue Longitude,Venue Category,Venue ID
5,Impact Kitchen,43.656369,-79.356980,Restaurant,5612b1cc498e3dd742af0dc8
19,El Catrin,43.650601,-79.358920,Mexican Restaurant,51ddecee498e1ffd34185d2f
20,Cocina Economica,43.654959,-79.365657,Mexican Restaurant,5542ab36498e2f92a8c248f2
24,Cluny Bistro & Boulangerie,43.650565,-79.357843,French Restaurant,53a22c92498ec91fda7ce133
25,Souvlaki Express,43.655584,-79.364438,Greek Restaurant,4bc39c914cdfc9b6f29c9721
...,...,...,...,...,...
2110,Chef Upstairs,43.701892,-79.387809,American Restaurant,4be0ab542aed2d7f0328c96f
2112,Oisie sushi,43.708301,-79.388424,Japanese Restaurant,4b942882f964a520d36b34e3
2114,Yasu,43.662837,-79.403217,Japanese Restaurant,5362c366498e602fbe1db395
2116,Piano Piano,43.662949,-79.402898,Italian Restaurant,56eb72e3498eefb98d82274b
2117,Rasa,43.662757,-79.403988,Restaurant,527d450111d25050de4ea0d8

In [33]:
toronto_rest_details = getRestaurntDetails(toronto_rest_3.get('Venue'),
                                            toronto_rest_3.get("Venue ID")
                                  )

toronto_rest_details.head(10)

ValueError: Length mismatch: Expected axis has 0 elements, new values have 4 elements

In [24]:
toronto_rest_3.rename(columns={"Venue":"Rest_name"},inplace=True)
toronto_rest_3.head()

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/pandas/core/frame.py:4238: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(**kwargs)

,Rest_name,Venue Latitude,Venue Longitude,Venue Category,Venue ID
5,Impact Kitchen,43.656369,-79.356980,Restaurant,5612b1cc498e3dd742af0dc8
19,El Catrin,43.650601,-79.358920,Mexican Restaurant,51ddecee498e1ffd34185d2f
20,Cocina Economica,43.654959,-79.365657,Mexican Restaurant,5542ab36498e2f92a8c248f2
24,Cluny Bistro & Boulangerie,43.650565,-79.357843,French Restaurant,53a22c92498ec91fda7ce133
25,Souvlaki Express,43.655584,-79.364438,Greek Restaurant,4bc39c914cdfc9b6f29c9721

In [25]:
toronto_rest_details2=pd.DataFrame()
#toronto_rest_onehot['Rest_name'] = toronto_rest_3['Rest_name'] 
toronto_rest_details = pd.merge(toronto_rest_details, toronto_rest_3, on='Rest_name')

toronto_rest_details2=toronto_rest_details[np.isfinite(toronto_rest_details['Rating'])]
print(toronto_rest_details2)

                             Rest_name           Price  Rating  Likes Count  \
0                       Impact Kitchen        Moderate     8.7           51
1                            El Catrin       Expensive     8.2          465
2                     Cocina Economica           Cheap     8.0           67
3           Cluny Bistro & Boulangerie  Very Expensive     8.3          182
4                     Souvlaki Express        Moderate     7.6            7
5                               Archeo        Moderate     7.6           20
6                                Izumi        Moderate     7.5           17
8                             Mercatto       Expensive     8.3           55
9                              Nando's        Moderate     8.1          179
10                           Sushi Box        Moderate     7.5           10
11                        Como En Casa           Cheap     8.4           56
12                         Tokyo Sushi        Moderate     8.0           33
13                  The Captain's Boil       Expensive     7.5           39
14     Hokkaido Ramen Santouka らーめん山頭火        Moderate     8.3          306
15                          Salad King        Moderate     8.1          490
16                                JOEY        Moderate     8.0          355
17                     Crepe Delicious           Cheap     8.4            8
18              Chipotle Mexican Grill        Moderate     7.6          172
19                        Spring Sushi        Moderate     7.6          193
20              Kinka Izakaya Original        Moderate     8.7          386
21                     Urban Herbivore        Moderate     8.0           47
22                          Milestones           Cheap     7.6           13
23                   JOEY Eaton Centre        Moderate     8.0            8
24                   Bourbon St. Grill           Cheap     7.7           11
25                Paramount Fine Foods        Moderate     7.6          202
26                       Kabul Express        Moderate     7.4           33
27                         Red Lobster        Moderate     8.1          136
28            Jack Astor's Bar & Grill        Moderate     7.3          264
29                         Ethiopiques        Moderate     7.3           21
30                  Trattoria Mercatto        Moderate     7.8          106
31    Scaddabush Italian Kitchen & Bar        Moderate     8.0          171
32  Ali Baba's - Yonge north of Dundas        Moderate     7.4            8
33              GB Hand-Pulled Noodles           Cheap     7.6           34
34                     Fine Asian Bowl        Moderate     6.9           28
35               Gyu-Kaku Japanese BBQ        Moderate     8.7           42
36                             Terroni       Expensive     8.6          275
37                   GEORGE Restaurant  Very Expensive     8.9           74
38                       Mystic Muffin           Cheap     8.8           29
39                      The Carbon Bar       Expensive     8.1          142
40                    Richmond Station       Expensive     9.1          249
41                                NAMI       Expensive     8.0           55
42                           Sukhothai        Moderate     8.6          217
43               La Bettola Di Terroni       Expensive     7.8           69
44                           The Chase       Expensive     8.2          141
45                                Leña        Moderate     8.1           70
46               Victoria's Restaurant        Moderate     7.8            6

    Venue Latitude  Venue Longitude                 Venue Category  \
0        43.656369       -79.356980                     Restaurant
1        43.650601       -79.358920             Mexican Restaurant
2        43.654959       -79.365657             Mexican Restaurant
3        43.650565       -79.357843              French Restaurant
4        43.655584       -79.364438               Greek Restaurant
5        43.650667       -79.359431             Italian Restaurant
6        43.649970       -79.360153               Asian Restaurant
8        43.660391       -79.387664             Italian Restaurant
9        43.661617       -79.386095          Portuguese Restaurant
10       43.662960       -79.386580               Sushi Restaurant
11       43.665160       -79.384796             Mexican Restaurant
12       43.665885       -79.386977               Sushi Restaurant
13       43.662375       -79.383535             Seafood Restaurant
14       43.656435       -79.377586               Ramen Restaurant
15       43.657601       -79.381620                Thai Restaurant
16       43.656094       -79.381878            American Restaurant
17       43.654536       -79.380889           Fast Food Restaurant
18       43.656860       -79.380910             Mexican Restaurant
19       43.656253       -79.380660               Sushi Restaurant
20       43.660596       -79.378891            Japanese Restaurant
21       43.654972       -79.380856  Vegetarian / Vegan Restaurant
22       43.656308       -79.380822           Fast Food Restaurant
23       43.655404       -79.381929                     Restaurant
24       43.655135       -79.380823           Fast Food Restaurant
25       43.655029       -79.380245      Middle Eastern Restaurant
26       43.656691       -79.376643      Middle Eastern Restaurant
27       43.656328       -79.383621             Seafood Restaurant
28       43.656019       -79.380326                     Restaurant
29       43.656513       -79.377078           Ethiopian Restaurant
30       43.654453       -79.380974             Italian Restaurant
31       43.658920       -79.382891             Italian Restaurant
32       43.657916       -79.381689      Middle Eastern Restaurant
33       43.656434       -79.383783             Chinese Restaurant
34       43.655387       -79.380326          Vietnamese Restaurant
35       43.651422       -79.375047            Japanese Restaurant
36       43.650927       -79.375602             Italian Restaurant
37       43.653346       -79.374445                     Restaurant
38       43.652484       -79.372655      Middle Eastern Restaurant
39       43.653367       -79.374965                     Restaurant
40       43.651569       -79.379266            American Restaurant
41       43.650853       -79.375887            Japanese Restaurant
42       43.648487       -79.374547                Thai Restaurant
43       43.651993       -79.378056             Italian Restaurant
44       43.650952       -79.379422        New American Restaurant
45       43.651722       -79.379205      Latin American Restaurant
46       43.649298       -79.376431                     Restaurant

                    Venue ID
0   5612b1cc498e3dd742af0dc8
1   51ddecee498e1ffd34185d2f
2   5542ab36498e2f92a8c248f2
3   53a22c92498ec91fda7ce133
4   4bc39c914cdfc9b6f29c9721
5   4ac3e6cef964a520629d20e3
6   50e88fc6e4b007fcbb57aae8
8   4a8355bff964a520d3fa1fe3
9   52d884c5498ecf5c7cafe5ab
10  4ecd63d96da162f1bb0f11c4
11  4fb593c0e4b05a76e2ab2951
12  4afca145f964a5208e2422e3
13  566387f1498e4003e174ef72
14  509e9ef6e4b0ab175389a6c5
15  4ad4c061f964a52095f720e3
16  4df909dfe4cd2129701c0690
17  4e5d8181a8092f63968617ee
18  4adc9148f964a520512d21e3
19  4fe4a773e4b0ef61f5212ecd
20  4b2bd898f964a52042bc24e3
21  4e5ff713ae60e9edf4ac0172
22  527dae3a498eaaa7f8fd063e
23  59246b5aad1789316b35d66c
24  4e8363c6e5fa5681e8c00e54
25  4c9cd4d37c096dcb9034c5d1
26  4adf8077f964a5202d7b21e3
27  4ae3398ff964a520ed9121e3
28  4ad9ffbbf964a520091d21e3
29  4c4e2474f53d0f47f18b13a6
30  4d306dd82748b60c62b6dba0
31  52f6816f11d24a43115dc834
32  568dcf20498e1601e2f8b87f
33  58e91d60e0adac258fcea481
34  4aea2b14f964a520ebb921e3
35  574ad72238fa943556d93b8e
36  4b49183ff964a520a46526e3
37  4af618daf964a520220122e3
38  4b72f550f964a5202e922de3
39  529e7344498e18bff5e60191
40  506db1a9e4b0a3f3b31412f0
41  4b999927f964a5207c8635e3
42  50b7c53616485cd9efad60d5
43  4c251062db519521621d2c3a
44  5214e7c111d2a83379eae21f
45  57d0a3fb498e0fb29e892eed
46  4ad4c05cf964a52006f620e3

In [26]:
toronto_rest_details2.head()

,Rest_name,Price,Rating,Likes Count,Venue Latitude,Venue Longitude,Venue Category,Venue ID
0,Impact Kitchen,Moderate,8.7,51,43.656369,-79.356980,Restaurant,5612b1cc498e3dd742af0dc8
1,El Catrin,Expensive,8.2,465,43.650601,-79.358920,Mexican Restaurant,51ddecee498e1ffd34185d2f
2,Cocina Economica,Cheap,8.0,67,43.654959,-79.365657,Mexican Restaurant,5542ab36498e2f92a8c248f2
3,Cluny Bistro & Boulangerie,Very Expensive,8.3,182,43.650565,-79.357843,French Restaurant,53a22c92498ec91fda7ce133
4,Souvlaki Express,Moderate,7.6,7,43.655584,-79.364438,Greek Restaurant,4bc39c914cdfc9b6f29c9721

<h2> Encode price</h2>

In [27]:
# one hot encoding
toronto_rest_onehot=pd.DataFrame()
toronto_rest_onehot = pd.get_dummies(toronto_rest_details2[['Price']], prefix="", prefix_sep="")
toronto_rest_onehot['Rest_name'] = toronto_rest_details2['Rest_name'] 
fixed_columns = [toronto_rest_onehot.columns[-1]] + list(toronto_rest_onehot.columns[:-1])
toronto_rest_onehot = toronto_rest_onehot[fixed_columns]

toronto_rest_onehot = pd.merge(toronto_rest_onehot, toronto_rest_details2, on='Rest_name')
toronto_rest_onehot.head()

,Rest_name,Cheap,Expensive,Moderate,Very Expensive,Price,Rating,Likes Count,Venue Latitude,Venue Longitude,Venue Category,Venue ID
0,Impact Kitchen,0,0,1,0,Moderate,8.7,51,43.656369,-79.356980,Restaurant,5612b1cc498e3dd742af0dc8
1,El Catrin,0,1,0,0,Expensive,8.2,465,43.650601,-79.358920,Mexican Restaurant,51ddecee498e1ffd34185d2f
2,Cocina Economica,1,0,0,0,Cheap,8.0,67,43.654959,-79.365657,Mexican Restaurant,5542ab36498e2f92a8c248f2
3,Cluny Bistro & Boulangerie,0,0,0,1,Very Expensive,8.3,182,43.650565,-79.357843,French Restaurant,53a22c92498ec91fda7ce133
4,Souvlaki Express,0,0,1,0,Moderate,7.6,7,43.655584,-79.364438,Greek Restaurant,4bc39c914cdfc9b6f29c9721

In [28]:
toronto_rest_onehot2=toronto_rest_onehot.loc[:,["Rest_name","Cheap",	"Expensive",	"Moderate",	"Very Expensive","Rating","Likes Count","Venue Latitude","Venue Longitude"]]
toronto_rest_onehot2.head()

,Rest_name,Cheap,Expensive,Moderate,Very Expensive,Rating,Likes Count,Venue Latitude,Venue Longitude
0,Impact Kitchen,0,0,1,0,8.7,51,43.656369,-79.356980
1,El Catrin,0,1,0,0,8.2,465,43.650601,-79.358920
2,Cocina Economica,1,0,0,0,8.0,67,43.654959,-79.365657
3,Cluny Bistro & Boulangerie,0,0,0,1,8.3,182,43.650565,-79.357843
4,Souvlaki Express,0,0,1,0,7.6,7,43.655584,-79.364438

In [29]:
toronto_rest_onehot3=toronto_rest_onehot2.loc[:,["Cheap","Expensive","Moderate","Very Expensive","Rating","Likes Count","Venue Latitude","Venue Longitude"]]

In [30]:
toronto_rest_onehot3.head(10)

,Cheap,Expensive,Moderate,Very Expensive,Rating,Likes Count,Venue Latitude,Venue Longitude
0,0,0,1,0,8.7,51,43.656369,-79.356980
1,0,1,0,0,8.2,465,43.650601,-79.358920
2,1,0,0,0,8.0,67,43.654959,-79.365657
3,0,0,0,1,8.3,182,43.650565,-79.357843
4,0,0,1,0,7.6,7,43.655584,-79.364438
5,0,0,1,0,7.6,20,43.650667,-79.359431
6,0,0,1,0,7.5,17,43.649970,-79.360153
7,0,1,0,0,8.3,55,43.660391,-79.387664
8,0,0,1,0,8.1,179,43.661617,-79.386095
9,0,0,1,0,7.5,10,43.662960,-79.386580

<h2>Normalization<h/2>

In [31]:
from sklearn.preprocessing import StandardScaler

X = toronto_rest_onehot3.values[:,:]
X = np.nan_to_num(X)
cluster_dataset = StandardScaler().fit_transform(X)
cluster_dataset

array([[-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01,  1.47011740e+00, -5.52592843e-01,
         2.44382043e-01,  2.54950599e+00],
       [-4.23659273e-01,  2.02758751e+00, -1.24721913e+00,
        -2.13200716e-01,  4.26515541e-01,  2.74014123e+00,
        -1.17927408e+00,  2.30425702e+00],
       [ 2.36038738e+00, -4.93196962e-01, -1.24721913e+00,
        -2.13200716e-01,  9.07479875e-03, -4.25337420e-01,
        -1.03552758e-01,  1.45283218e+00],
       [-4.23659273e-01, -4.93196962e-01, -1.24721913e+00,
         4.69041576e+00,  6.35235912e-01,  4.89310934e-01,
        -1.18806641e+00,  2.44041661e+00],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01, -8.25806686e-01, -9.02545257e-01,
         5.07219691e-02,  1.60690019e+00],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01, -8.25806686e-01, -7.99150226e-01,
        -1.16286163e+00,  2.23975263e+00],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01, -1.03452706e+00, -8.23010618e-01,
        -1.33500966e+00,  2.14842809e+00],
       [-4.23659273e-01,  2.02758751e+00, -1.24721913e+00,
        -2.13200716e-01,  6.35235912e-01, -5.20778988e-01,
         1.23723115e+00, -1.32841612e+00],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01,  2.17795170e-01,  4.65450543e-01,
         1.53988165e+00, -1.13014522e+00],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01, -1.03452706e+00, -8.78684865e-01,
         1.87124602e+00, -1.19138803e+00],
       [ 2.36038738e+00, -4.93196962e-01, -1.24721913e+00,
        -2.13200716e-01,  8.43956284e-01, -5.12825524e-01,
         2.41438340e+00, -9.65930384e-01],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01,  9.07479875e-03, -6.95755194e-01,
         2.59341657e+00, -1.24154689e+00],
       [-4.23659273e-01,  2.02758751e+00, -1.24721913e+00,
        -2.13200716e-01, -1.03452706e+00, -6.48034411e-01,
         1.72694189e+00, -8.06534140e-01],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01,  6.35235912e-01,  1.47554046e+00,
         2.60844963e-01, -5.47758075e-02],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01,  2.17795170e-01,  2.93897783e+00,
         5.48601758e-01, -5.64499532e-01],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01,  9.07479875e-03,  1.86526020e+00,
         1.76540586e-01, -5.97142753e-01],
       [ 2.36038738e+00, -4.93196962e-01, -1.24721913e+00,
        -2.13200716e-01,  8.43956284e-01, -8.94591793e-01,
        -2.07814075e-01, -4.72143943e-01],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01, -8.25806686e-01,  4.09776295e-01,
         3.65697466e-01, -4.74816196e-01],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01, -8.25806686e-01,  5.76799038e-01,
         2.15755824e-01, -4.43163559e-01],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01,  1.47011740e+00,  2.11181758e+00,
         1.28794339e+00, -2.19680422e-01],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01,  9.07479875e-03, -5.84406699e-01,
        -1.00352482e-01, -4.67936086e-01],
       [ 2.36038738e+00, -4.93196962e-01, -1.24721913e+00,
        -2.13200716e-01, -8.25806686e-01, -8.54824474e-01,
         2.29358348e-01, -4.63732667e-01],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01,  9.07479875e-03, -8.94591793e-01,
         6.26415702e-03, -6.03585173e-01],
       [ 2.36038738e+00, -4.93196962e-01, -1.24721913e+00,
        -2.13200716e-01, -6.17086315e-01, -8.70731401e-01,
        -6.00488408e-02, -4.63761228e-01],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01, -8.25806686e-01,  6.48380214e-01,
        -8.63195454e-02, -3.90789691e-01],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01, -1.24324743e+00, -6.95755194e-01,
         3.24098862e-01,  6.44316585e-02],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01,  2.17795170e-01,  1.23451593e-01,
         2.34384102e-01, -8.17433428e-01],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01, -1.45196780e+00,  1.14149498e+00,
         1.58212458e-01, -4.00948603e-01],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01, -1.45196780e+00, -7.91196762e-01,
         2.79984159e-01,  9.50519239e-03],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01, -4.08365944e-01, -1.15152326e-01,
        -2.28385739e-01, -4.82918135e-01],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01,  9.07479875e-03,  4.01822831e-01,
         8.74238587e-01, -7.25182546e-01],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01, -1.24324743e+00, -8.94591793e-01,
         6.26342576e-01, -5.73296715e-01],
       [ 2.36038738e+00, -4.93196962e-01, -1.24721913e+00,
        -2.13200716e-01, -8.25806686e-01, -6.87801731e-01,
         2.60603699e-01, -8.37873641e-01],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01, -2.28684928e+00, -7.35522514e-01,
         2.01868737e-03, -4.01060601e-01],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01,  1.47011740e+00, -6.24174019e-01,
        -9.76494066e-01,  2.66159998e-01],
       [-4.23659273e-01,  2.02758751e+00, -1.24721913e+00,
        -2.13200716e-01,  1.26139703e+00,  1.22898308e+00,
        -1.09874273e+00,  1.96010904e-01],
       [-4.23659273e-01, -4.93196962e-01, -1.24721913e+00,
         4.69041576e+00,  1.88755814e+00, -3.69663172e-01,
        -5.01549217e-01,  3.42245005e-01],
       [ 2.36038738e+00, -4.93196962e-01, -1.24721913e+00,
        -2.13200716e-01,  1.67883777e+00, -7.27569050e-01,
        -7.14539949e-01,  5.68488227e-01],
       [-4.23659273e-01,  2.02758751e+00, -1.24721913e+00,
        -2.13200716e-01,  2.17795170e-01,  1.71172376e-01,
        -4.96456987e-01,  2.76496034e-01],
       [-4.23659273e-01,  2.02758751e+00, -1.24721913e+00,
        -2.13200716e-01,  2.30499888e+00,  1.02219302e+00,
        -9.40345836e-01, -2.67039255e-01],
       [-4.23659273e-01,  2.02758751e+00, -1.24721913e+00,
        -2.13200716e-01,  9.07479875e-03, -5.20778988e-01,
        -1.11691883e+00,  1.59933548e-01],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01,  1.26139703e+00,  7.67682173e-01,
        -1.70098173e+00,  3.29297670e-01],
       [-4.23659273e-01,  2.02758751e+00, -1.24721913e+00,
        -2.13200716e-01, -4.08365944e-01, -4.09430492e-01,
        -8.35546837e-01, -1.14100805e-01],
       [-4.23659273e-01,  2.02758751e+00, -1.24721913e+00,
        -2.13200716e-01,  4.26515541e-01,  1.63218912e-01,
        -1.09257641e+00, -2.86764684e-01],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01,  2.17795170e-01, -4.01477028e-01,
        -9.02513178e-01, -2.59337634e-01],
       [-4.23659273e-01, -4.93196962e-01,  8.01783726e-01,
        -2.13200716e-01, -4.08365944e-01, -9.10498721e-01,
        -1.50074330e+00,  9.12829498e-02]])

</h2> Cluster</h2>

In [33]:
kclusters=4

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(cluster_dataset)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:30]

array([1, 0, 2, 3, 1, 1, 1, 0, 1, 1, 2, 1, 0, 1, 1, 1, 2, 1, 1, 1, 1, 2,
       1, 2, 1, 1, 1, 1, 1, 1], dtype=int32)

In [34]:
df5_toronto=pd.DataFrame()
df5_toronto["Cluster Labels"]=kmeans.labels_
df5_toronto=pd.concat([df5_toronto,toronto_rest_details2], axis=1)
df5_toronto

,Cluster Labels,Rest_name,Price,Rating,Likes Count,Venue Latitude,Venue Longitude,Venue Category,Venue ID
0,1.0,Impact Kitchen,Moderate,8.7,51.0,43.656369,-79.356980,Restaurant,5612b1cc498e3dd742af0dc8
1,0.0,El Catrin,Expensive,8.2,465.0,43.650601,-79.358920,Mexican Restaurant,51ddecee498e1ffd34185d2f
2,2.0,Cocina Economica,Cheap,8.0,67.0,43.654959,-79.365657,Mexican Restaurant,5542ab36498e2f92a8c248f2
3,3.0,Cluny Bistro & Boulangerie,Very Expensive,8.3,182.0,43.650565,-79.357843,French Restaurant,53a22c92498ec91fda7ce133
4,1.0,Souvlaki Express,Moderate,7.6,7.0,43.655584,-79.364438,Greek Restaurant,4bc39c914cdfc9b6f29c9721
5,1.0,Archeo,Moderate,7.6,20.0,43.650667,-79.359431,Italian Restaurant,4ac3e6cef964a520629d20e3
6,1.0,Izumi,Moderate,7.5,17.0,43.649970,-79.360153,Asian Restaurant,50e88fc6e4b007fcbb57aae8
7,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1.0,Mercatto,Expensive,8.3,55.0,43.660391,-79.387664,Italian Restaurant,4a8355bff964a520d3fa1fe3
9,1.0,Nando's,Moderate,8.1,179.0,43.661617,-79.386095,Portuguese Restaurant,52d884c5498ecf5c7cafe5ab
10,2.0,Sushi Box,Moderate,7.5,10.0,43.662960,-79.386580,Sushi Restaurant,4ecd63d96da162f1bb0f11c4
11,1.0,Como En Casa,Cheap,8.4,56.0,43.665160,-79.384796,Mexican Restaurant,4fb593c0e4b05a76e2ab2951
12,0.0,Tokyo Sushi,Moderate,8.0,33.0,43.665885,-79.386977,Sushi Restaurant,4afca145f964a5208e2422e3
13,1.0,The Captain's Boil,Expensive,7.5,39.0,43.662375,-79.383535,Seafood Restaurant,566387f1498e4003e174ef72
14,1.0,Hokkaido Ramen Santouka らーめん山頭火,Moderate,8.3,306.0,43.656435,-79.377586,Ramen Restaurant,509e9ef6e4b0ab175389a6c5
15,1.0,Salad King,Moderate,8.1,490.0,43.657601,-79.381620,Thai Restaurant,4ad4c061f964a52095f720e3
16,2.0,JOEY,Moderate,8.0,355.0,43.656094,-79.381878,American Restaurant,4df909dfe4cd2129701c0690
17,1.0,Crepe Delicious,Cheap,8.4,8.0,43.654536,-79.380889,Fast Food Restaurant,4e5d8181a8092f63968617ee
18,1.0,Chipotle Mexican Grill,Moderate,7.6,172.0,43.656860,-79.380910,Mexican Restaurant,4adc9148f964a520512d21e3
19,1.0,Spring Sushi,Moderate,7.6,193.0,43.656253,-79.380660,Sushi Restaurant,4fe4a773e4b0ef61f5212ecd
20,1.0,Kinka Izakaya Original,Moderate,8.7,386.0,43.660596,-79.378891,Japanese Restaurant,4b2bd898f964a52042bc24e3
21,2.0,Urban Herbivore,Moderate,8.0,47.0,43.654972,-79.380856,Vegetarian / Vegan Restaurant,4e5ff713ae60e9edf4ac0172
22,1.0,Milestones,Cheap,7.6,13.0,43.656308,-79.380822,Fast Food Restaurant,527dae3a498eaaa7f8fd063e
23,2.0,JOEY Eaton Centre,Moderate,8.0,8.0,43.655404,-79.381929,Restaurant,59246b5aad1789316b35d66c
24,1.0,Bourbon St. Grill,Cheap,7.7,11.0,43.655135,-79.380823,Fast Food Restaurant,4e8363c6e5fa5681e8c00e54
25,1.0,Paramount Fine Foods,Moderate,7.6,202.0,43.655029,-79.380245,Middle Eastern Restaurant,4c9cd4d37c096dcb9034c5d1
26,1.0,Kabul Express,Moderate,7.4,33.0,43.656691,-79.376643,Middle Eastern Restaurant,4adf8077f964a5202d7b21e3
27,1.0,Red Lobster,Moderate,8.1,136.0,43.656328,-79.383621,Seafood Restaurant,4ae3398ff964a520ed9121e3
28,1.0,Jack Astor's Bar & Grill,Moderate,7.3,264.0,43.656019,-79.380326,Restaurant,4ad9ffbbf964a520091d21e3
29,1.0,Ethiopiques,Moderate,7.3,21.0,43.656513,-79.377078,Ethiopian Restaurant,4c4e2474f53d0f47f18b13a6
30,1.0,Trattoria Mercatto,Moderate,7.8,106.0,43.654453,-79.380974,Italian Restaurant,4d306dd82748b60c62b6dba0
31,1.0,Scaddabush Italian Kitchen & Bar,Moderate,8.0,171.0,43.658920,-79.382891,Italian Restaurant,52f6816f11d24a43115dc834
32,2.0,Ali Baba's - Yonge north of Dundas,Moderate,7.4,8.0,43.657916,-79.381689,Middle Eastern Restaurant,568dcf20498e1601e2f8b87f
33,1.0,GB Hand-Pulled Noodles,Cheap,7.6,34.0,43.656434,-79.383783,Chinese Restaurant,58e91d60e0adac258fcea481
34,1.0,Fine Asian Bowl,Moderate,6.9,28.0,43.655387,-79.380326,Vietnamese Restaurant,4aea2b14f964a520ebb921e3
35,0.0,Gyu-Kaku Japanese BBQ,Moderate,8.7,42.0,43.651422,-79.375047,Japanese Restaurant,574ad72238fa943556d93b8e
36,3.0,Terroni,Expensive,8.6,275.0,43.650927,-79.375602,Italian Restaurant,4b49183ff964a520a46526e3
37,2.0,GEORGE Restaurant,Very Expensive,8.9,74.0,43.653346,-79.374445,Restaurant,4af618daf964a520220122e3
38,0.0,Mystic Muffin,Cheap,8.8,29.0,43.652484,-79.372655,Middle Eastern Restaurant,4b72f550f964a5202e922de3
39,0.0,The Carbon Bar,Expensive,8.1,142.0,43.653367,-79.374965,Restaurant,529e7344498e18bff5e60191
40,0.0,Richmond Station,Expensive,9.1,249.0,43.651569,-79.379266,American Restaurant,506db1a9e4b0a3f3b31412f0
41,1.0,NAMI,Expensive,8.0,55.0,43.650853,-79.375887,Japanese Restaurant,4b999927f964a5207c8635e3
42,0.0,Sukhothai,Moderate,8.6,217.0,43.648487,-79.374547,Thai Restaurant,50b7c53616485cd9efad60d5
43,0.0,La Bettola Di Terroni,Expensive,7.8,69.0,43.651993,-79.378056,Italian Restaurant,4c251062db519521621d2c3a
44,1.0,The Chase,Expensive,8.2,141.0,43.650952,-79.379422,New American Restaurant,5214e7c111d2a83379eae21f
45,1.0,Leña,Moderate,8.1,70.0,43.651722,-79.379205,Latin American Restaurant,57d0a3fb498e0fb29e892eed
46,NaN,Victoria's Restaurant,Moderate,7.8,6.0,43.649298,-79.376431,Restaurant,4ad4c05cf964a52006f620e3

In [35]:
df5_toronto.dropna(inplace=True)
df5_toronto.drop_duplicates(inplace=True)
df5_toronto=df5_toronto[np.isfinite(df5_toronto['Rating'])]
df5_toronto.head()

,Cluster Labels,Rest_name,Price,Rating,Likes Count,Venue Latitude,Venue Longitude,Venue Category,Venue ID
0,1.0,Impact Kitchen,Moderate,8.7,51.0,43.656369,-79.356980,Restaurant,5612b1cc498e3dd742af0dc8
1,0.0,El Catrin,Expensive,8.2,465.0,43.650601,-79.358920,Mexican Restaurant,51ddecee498e1ffd34185d2f
2,2.0,Cocina Economica,Cheap,8.0,67.0,43.654959,-79.365657,Mexican Restaurant,5542ab36498e2f92a8c248f2
3,3.0,Cluny Bistro & Boulangerie,Very Expensive,8.3,182.0,43.650565,-79.357843,French Restaurant,53a22c92498ec91fda7ce133
4,1.0,Souvlaki Express,Moderate,7.6,7.0,43.655584,-79.364438,Greek Restaurant,4bc39c914cdfc9b6f29c9721

In [36]:
df5_toronto.describe()

       Cluster Labels     Rating  Likes Count  Venue Latitude  Venue Longitude
count       45.000000  45.000000    45.000000       45.000000        45.000000
mean         1.066667   8.000000   123.022222       43.655514       -79.377169
std          0.719848   0.488969   127.367487        0.004037         0.008090
min          0.000000   6.900000     7.000000       43.648487       -79.387664
25%          1.000000   7.600000    29.000000       43.651993       -79.381689
50%          1.000000   8.000000    67.000000       43.655404       -79.380245
75%          1.000000   8.300000   182.000000       43.656691       -79.375047
max          3.000000   9.100000   490.000000       43.665885       -79.356980

In [37]:
df5_toronto[df5_toronto["Cluster Labels"]==3].head(20)

,Cluster Labels,Rest_name,Price,Rating,Likes Count,Venue Latitude,Venue Longitude,Venue Category,Venue ID
3,3.0,Cluny Bistro & Boulangerie,Very Expensive,8.3,182.0,43.650565,-79.357843,French Restaurant,53a22c92498ec91fda7ce133
36,3.0,Terroni,Expensive,8.6,275.0,43.650927,-79.375602,Italian Restaurant,4b49183ff964a520a46526e3

In [38]:
df5_toronto.loc[df5_toronto["Price"]=="Cheap",:].shape

(7, 9)

In [39]:
df5_toronto.loc[df5_toronto["Price"]=="Moderate",:].shape

(27, 9)

In [40]:
df5_toronto.loc[df5_toronto["Price"]=="Expensive",:].shape

(9, 9)

In [41]:
df5_toronto.loc[df5_toronto["Price"]=="Very Expensive",:].shape

(2, 9)

<h2> Visualize the clusters </h2>

In [43]:
# create map
map_clusters = folium.Map(location=[43.651070, -79.347015], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, kclusters))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(df5_toronto['Venue Latitude'], df5_toronto['Venue Longitude'], df5_toronto['Rest_name'], df5_toronto['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[int(cluster)-2],
        fill=True,
        fill_color=rainbow[int(cluster)-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

<h2> 10 Top types cuisunes categories in Toronto</h2>

In [44]:
toronto_restaurants=pd.DataFrame()
toronto_restaurants["restaurant_category"]=toronto_restaurants_array[0]
toronto_restaurants["restaurant_category_count"]=toronto_restaurants_array[1]
toronto_restaurants.sort_values('restaurant_category_count',inplace=True,ascending=False)
toronto_restaurants = toronto_restaurants[toronto_restaurants.restaurant_category != "Restaurant"]
toronto_restaurants.head(10)

              restaurant_category  restaurant_category_count
26             Italian Restaurant                         76
1             American Restaurant                         47
27            Japanese Restaurant                         44
42               Sushi Restaurant                         41
46  Vegetarian / Vegan Restaurant                         39
40             Seafood Restaurant                         38
44                Thai Restaurant                         37
3                Asian Restaurant                         27
23               Greek Restaurant                         25
47          Vietnamese Restaurant                         24

<h2> REstaurants in New York</h2>

In [116]:
!wget -q -O 'newyork_data.json' https://cocl.us/new_york_dataset
print('Data downloaded!')

Data downloaded!

In [117]:
with open('newyork_data.json') as json_data:
    newyork_data = json.load(json_data)

In [118]:
neighborhoods_data = newyork_data['features']

In [119]:
# define the dataframe columns
column_names = ['Borough', 'Neighborhood', 'Latitude', 'Longitude'] 

# instantiate the dataframe
nyc_neighborhoods = pd.DataFrame(columns=column_names)
nyc_neighborhoods.head()

Empty DataFrame
Columns: [Borough, Neighborhood, Latitude, Longitude]
Index: []

In [5]:
for data in neighborhoods_data:
    borough = neighborhood_name = data['properties']['borough'] 
    neighborhood_name = data['properties']['name']
        
    neighborhood_latlon = data['geometry']['coordinates']
    neighborhood_lat = neighborhood_latlon[1]
    neighborhood_lon = neighborhood_latlon[0]
    
    nyc_neighborhoods = nyc_neighborhoods.append({'Borough': borough,
                                          'Neighborhood': neighborhood_name,
                                          'Latitude': neighborhood_lat,
                                          'Longitude': neighborhood_lon}, ignore_index=True)

NameError: name 'neighborhoods_data' is not defined

In [6]:
nyc_neighborhoods=nyc_neighborhoods.loc[nyc_neighborhoods["Borough"]=="Manhattan",:]
nyc_neighborhoods.head(20)

NameError: name 'nyc_neighborhoods' is not defined

In [95]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        #print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            500, 
            100)
            
        # make the GET request
        #print(requests.get(url).json())
        group_data = requests.get(url).json().get("response").get('groups')
        
        if group_data:
            results = group_data[0].get('items')
        else:
            results=''
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v.get("venue").get("id"),
            v.get('venue').get('name'), 
            v.get('venue').get('location').get('lat'), 
            v.get('venue').get('location').get('lng'),  
            v.get('venue').get('categories')[0].get('name')) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue ID',
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

<h2>Nearby venues</h2>

In [96]:
nyc_venues = getNearbyVenues(names=nyc_neighborhoods['Neighborhood'],
                                   latitudes=nyc_neighborhoods['Latitude'],
                                   longitudes=nyc_neighborhoods['Longitude']
                                  )
print(nyc_venues.shape)

print(np.unique(nyc_venues["Venue Category"],return_counts=True))

(3304, 8)
(array(['Accessories Store', 'Adult Boutique', 'Afghan Restaurant',
       'African Restaurant', 'American Restaurant', 'Antique Shop',
       'Arcade', 'Arepa Restaurant', 'Argentinian Restaurant',
       'Art Gallery', 'Art Museum', 'Arts & Crafts Store',
       'Asian Restaurant', 'Athletics & Sports', 'Auditorium',
       'Australian Restaurant', 'Austrian Restaurant', 'BBQ Joint',
       'Baby Store', 'Bagel Shop', 'Bakery', 'Bank', 'Bar',
       'Baseball Field', 'Basketball Court', 'Bed & Breakfast',
       'Beer Bar', 'Beer Garden', 'Beer Store', 'Big Box Store',
       'Bike Rental / Bike Share', 'Bike Shop', 'Bike Trail', 'Bistro',
       'Board Shop', 'Boat or Ferry', 'Bookstore', 'Boutique',
       'Boxing Gym', 'Brazilian Restaurant', 'Breakfast Spot',
       'Bridal Shop', 'Bridge', 'Bubble Tea Shop', 'Building',
       'Burger Joint', 'Burrito Place', 'Bus Line', 'Bus Station',
       'Butcher', 'Cafeteria', 'Café', 'Cajun / Creole Restaurant',
       'Cambodian Restaurant', 'Camera Store', 'Candy Store',
       'Cantonese Restaurant', 'Caribbean Restaurant',
       'Caucasian Restaurant', 'Cheese Shop', 'Chinese Restaurant',
       'Chocolate Shop', 'Christmas Market', 'Circus', 'Climbing Gym',
       'Clothing Store', 'Club House', 'Cocktail Bar', 'Coffee Shop',
       'College Academic Building', 'College Arts Building',
       'College Bookstore', 'College Cafeteria', 'College Theater',
       'Comedy Club', 'Community Center', 'Concert Hall',
       'Convenience Store', 'Cooking School', 'Cosmetics Shop',
       'Coworking Space', 'Creperie', 'Cuban Restaurant',
       'Cultural Center', 'Cupcake Shop', 'Cycle Studio',
       'Czech Restaurant', 'Dance Studio', 'Daycare', 'Deli / Bodega',
       'Department Store', 'Design Studio', 'Dessert Shop',
       'Dim Sum Restaurant', 'Diner', 'Discount Store', 'Dive Bar',
       "Doctor's Office", 'Dog Run', 'Donut Shop', 'Drugstore',
       'Dry Cleaner', 'Dumpling Restaurant', 'Duty-free Shop',
       'Eastern European Restaurant', 'Electronics Store',
       'Empanada Restaurant', 'English Restaurant',
       'Ethiopian Restaurant', 'Event Space', 'Exhibit',
       'Falafel Restaurant', 'Farmers Market', 'Fast Food Restaurant',
       'Filipino Restaurant', 'Financial or Legal Service', 'Fish Market',
       'Flea Market', 'Flower Shop', 'Food & Drink Shop', 'Food Court',
       'Food Stand', 'Food Truck', 'Fountain', 'French Restaurant',
       'Fried Chicken Joint', 'Frozen Yogurt Shop',
       'Furniture / Home Store', 'Gaming Cafe', 'Garden', 'Garden Center',
       'Gas Station', 'Gastropub', 'Gay Bar',
       'General College & University', 'General Entertainment',
       'German Restaurant', 'Gift Shop', 'Golf Course', 'Gourmet Shop',
       'Greek Restaurant', 'Grocery Store', 'Gym', 'Gym / Fitness Center',
       'Gym Pool', 'Gymnastics Gym', 'Harbor / Marina', 'Hardware Store',
       'Hawaiian Restaurant', 'Health & Beauty Service',
       'Health Food Store', 'Heliport', 'High School',
       'Himalayan Restaurant', 'Historic Site', 'History Museum',
       'Hobby Shop', 'Hookah Bar', 'Hostel', 'Hot Dog Joint', 'Hotel',
       'Hotel Bar', 'Hotpot Restaurant', 'Ice Cream Shop',
       'Indian Restaurant', 'Indie Movie Theater', 'Indie Theater',
       'Irish Pub', 'Israeli Restaurant', 'Italian Restaurant',
       'Japanese Curry Restaurant', 'Japanese Restaurant', 'Jazz Club',
       'Jewelry Store', 'Jewish Restaurant', 'Juice Bar', 'Karaoke Bar',
       'Kebab Restaurant', 'Kids Store', 'Kitchen Supply Store',
       'Korean Restaurant', 'Kosher Restaurant',
       'Latin American Restaurant', 'Laundry Service',
       'Leather Goods Store', 'Lebanese Restaurant', 'Library',
       'Lingerie Store', 'Liquor Store', 'Lounge', 'Malay Restaurant',
       'Market', 'Martial Arts Dojo', 'Massage Studio', 'Medical Center',
       'Mediterranean Restaurant', 'Memorial Site', "Men's Store",
       'Metro Station', 'Mexican Restaurant', 'Middle Eastern Restaurant',
       'Mini Golf', 'Miscellaneous Shop', 'Mobile Phone Shop',
       'Modern European Restaurant', 'Molecular Gastronomy Restaurant',
       'Monument / Landmark', 'Moroccan Restaurant', 'Movie Theater',
       'Museum', 'Music School', 'Music Store', 'Music Venue',
       'Nail Salon', 'New American Restaurant', 'Newsstand', 'Nightclub',
       'Non-Profit', 'Noodle House', 'Office', 'Opera House',
       'Optical Shop', 'Organic Grocery', 'Outdoor Sculpture',
       'Outdoors & Recreation', 'Paella Restaurant',
       'Pakistani Restaurant', 'Paper / Office Supplies Store', 'Park',
       'Pedestrian Plaza', 'Performing Arts Venue', 'Persian Restaurant',
       'Peruvian Restaurant', 'Pet Café', 'Pet Service', 'Pet Store',
       'Pharmacy', 'Photography Studio', 'Physical Therapist',
       'Piano Bar', 'Pie Shop', 'Pilates Studio', 'Pizza Place',
       'Playground', 'Plaza', 'Poke Place', 'Pool', 'Pub', 'Public Art',
       'Ramen Restaurant', 'Record Shop', 'Recreation Center',
       'Rental Car Location', 'Residential Building (Apartment / Condo)',
       'Resort', 'Rest Area', 'Restaurant', 'Rock Club', 'Roof Deck',
       'Russian Restaurant', 'Sake Bar', 'Salad Place',
       'Salon / Barbershop', 'Sandwich Place', 'Scandinavian Restaurant',
       'Scenic Lookout', 'School', 'Sculpture Garden',
       'Seafood Restaurant', 'Shanghai Restaurant', 'Shipping Store',
       'Shoe Store', 'Shopping Mall', 'Skate Park', 'Skating Rink',
       'Ski Shop', 'Smoke Shop', 'Smoothie Shop', 'Snack Place',
       'Soba Restaurant', 'Soccer Field', 'Social Club', 'Soup Place',
       'South American Restaurant', 'South Indian Restaurant',
       'Southern / Soul Food Restaurant', 'Spa', 'Spanish Restaurant',
       'Speakeasy', 'Spiritual Center', 'Sporting Goods Shop',
       'Sports Bar', 'Sports Club', 'Steakhouse', 'Street Art',
       'Strip Club', 'Supermarket', 'Supplement Shop', 'Sushi Restaurant',
       'Swiss Restaurant', 'Szechuan Restaurant', 'Taco Place',
       'Tailor Shop', 'Taiwanese Restaurant', 'Tapas Restaurant',
       'Tattoo Parlor', 'Tea Room', 'Tennis Court', 'Tennis Stadium',
       'Thai Restaurant', 'Theater', 'Theme Park Ride / Attraction',
       'Thrift / Vintage Store', 'Tiki Bar', 'Tourist Information Center',
       'Toy / Game Store', 'Track', 'Trail', 'Tree', 'Turkish Restaurant',
       'Udon Restaurant', 'Used Bookstore',
       'Vegetarian / Vegan Restaurant', 'Venezuelan Restaurant',
       'Veterinarian', 'Video Game Store', 'Video Store',
       'Vietnamese Restaurant', 'Volleyball Court', 'Waterfront',
       'Whisky Bar', 'Wine Bar', 'Wine Shop', 'Wings Joint',
       "Women's Store", 'Yoga Studio'], dtype=object), array([  5,   2,   1,   3,  78,   2,   1,   2,   5,  31,   4,   5,  13,
         3,   1,   5,   2,   5,   1,  21,  74,   7,  54,   1,   2,   1,
         9,   4,   4,   1,   3,   1,   1,   4,   1,   6,  26,  27,   4,
         2,   7,   3,   2,  10,   7,  27,   4,   1,   3,   2,   1,  77,
         1,   1,   2,   5,   1,   9,   2,   5,  49,   3,   1,   1,   2,
        37,   2,  65, 131,   1,   1,   1,   1,   1,   6,   1,   8,   4,
         1,  36,   1,   3,  10,   1,  11,  19,   1,   5,   1,  36,   7,
         3,  27,   4,  19,   2,   1,   2,  14,   6,   1,   1,   4,   1,
         1,   5,   1,   1,   4,   8,   9,   8,  11,   4,   3,   1,   1,
         2,   4,   3,   7,   1,  18,   2,  53,   9,   3,  21,   1,   9,
         2,   2,   9,   1,   1,   3,   3,  17,   1,  20,  20,  33,  59,
        57,   1,   1,   2,   1,   4,   7,   4,   2,   2,   1,   8,   4,
         3,   1,   1,   3,  61,  12,   3,  40,  31,   6,   5,   2,   3,
       125,   3,  48,   8,   3,   3,  19,   5,   1,   2,   1,  22,   1,
        13,   1,   2,   1,   2,  10,  10,  13,   2,   5,   9,   3,   1,
        27,   3,  10,   1,  53,   6,   1,   5,   4,   1,   1,   5,   2,
         6,   7,   3,   1,   5,   3,  25,   1,   6,   2,   8,   2,   2,
        11,   3,   1,   1,   2,   1,   5,  64,   1,  10,   1,   6,   3,
         1,  14,  11,   1,   1,   1,   1,  11,  71,  17,  19,   5,   3,
        17,   3,  19,   2,   1,   2,   4,   1,   1,  23,   6,   7,   1,
         3,  15,  20,  48,   1,   8,   5,   2,  33,   3,   3,  12,   4,
         1,   1,   1,   5,   1,   5,   1,   1,   1,   3,   1,   1,   3,
        46,  18,  14,   1,  18,   2,   1,  27,   3,   2,  12,   4,  44,
         1,   3,  13,   3,   2,   9,   3,   8,   5,   2,  26,  28,   1,
         3,   2,   1,   7,   1,   4,   1,   6,   2,   2,  23,   1,   1,
         1,   1,  21,   1,   1,   2,  43,  44,   2,  17,  34]))

In [97]:
print('There are {} uniques categories.'.format(len(nyc_venues['Venue Category'].unique())))

There are 336 uniques categories.

<h2>Unique categories</h2>

In [98]:
nyc_restaurants_array=np.unique(nyc_venues["Venue Category"].loc[nyc_venues["Venue Category"].str.contains("Restaurant")],return_counts=True)
print(len(nyc_restaurants_array[0]))
print(nyc_restaurants_array)

77
(array(['Afghan Restaurant', 'African Restaurant', 'American Restaurant',
       'Arepa Restaurant', 'Argentinian Restaurant', 'Asian Restaurant',
       'Australian Restaurant', 'Austrian Restaurant',
       'Brazilian Restaurant', 'Cajun / Creole Restaurant',
       'Cambodian Restaurant', 'Cantonese Restaurant',
       'Caribbean Restaurant', 'Caucasian Restaurant',
       'Chinese Restaurant', 'Cuban Restaurant', 'Czech Restaurant',
       'Dim Sum Restaurant', 'Dumpling Restaurant',
       'Eastern European Restaurant', 'Empanada Restaurant',
       'English Restaurant', 'Ethiopian Restaurant', 'Falafel Restaurant',
       'Fast Food Restaurant', 'Filipino Restaurant', 'French Restaurant',
       'German Restaurant', 'Greek Restaurant', 'Hawaiian Restaurant',
       'Himalayan Restaurant', 'Hotpot Restaurant', 'Indian Restaurant',
       'Israeli Restaurant', 'Italian Restaurant',
       'Japanese Curry Restaurant', 'Japanese Restaurant',
       'Jewish Restaurant', 'Kebab Restaurant', 'Korean Restaurant',
       'Kosher Restaurant', 'Latin American Restaurant',
       'Lebanese Restaurant', 'Malay Restaurant',
       'Mediterranean Restaurant', 'Mexican Restaurant',
       'Middle Eastern Restaurant', 'Modern European Restaurant',
       'Molecular Gastronomy Restaurant', 'Moroccan Restaurant',
       'New American Restaurant', 'Paella Restaurant',
       'Pakistani Restaurant', 'Persian Restaurant',
       'Peruvian Restaurant', 'Ramen Restaurant', 'Restaurant',
       'Russian Restaurant', 'Scandinavian Restaurant',
       'Seafood Restaurant', 'Shanghai Restaurant', 'Soba Restaurant',
       'South American Restaurant', 'South Indian Restaurant',
       'Southern / Soul Food Restaurant', 'Spanish Restaurant',
       'Sushi Restaurant', 'Swiss Restaurant', 'Szechuan Restaurant',
       'Taiwanese Restaurant', 'Tapas Restaurant', 'Thai Restaurant',
       'Turkish Restaurant', 'Udon Restaurant',
       'Vegetarian / Vegan Restaurant', 'Venezuelan Restaurant',
       'Vietnamese Restaurant'], dtype=object), array([  1,   3,  78,   2,   5,  13,   5,   2,   2,   1,   1,   1,   9,
         2,  49,  10,   1,   4,   4,   1,   1,   1,   4,   8,   4,   3,
        53,   3,  20,   4,   1,   3,  31,   3, 125,   3,  48,   3,   1,
        22,   1,  13,   1,   2,  27,  53,   6,   1,   1,   2,  25,   2,
         1,   1,   6,  19,  23,   1,   1,  33,   3,   1,   1,   1,   3,
        18,  44,   1,   3,   2,   9,  26,   6,   2,  23,   1,  21]))

In [99]:
nyc_rest_2=nyc_venues.loc[nyc_venues["Venue Category"].str.contains("Restaurant")]
nyc_rest_2=nyc_rest_2.loc[:,["Venue","Venue Latitude","Venue Longitude","Venue Category","Venue ID"]]
nyc_rest_2.head()

,Venue,Venue Latitude,Venue Longitude,Venue Category,Venue ID
6,Land & Sea Restaurant,40.877885,-73.905873,Seafood Restaurant,4b9c9c6af964a520b27236e3
12,Boston Market,40.877430,-73.905412,American Restaurant,585c205665e7c70a2f1055ea
25,Kiki's,40.714476,-73.992036,Greek Restaurant,5521c2ff498ebe2368634187
28,Spicy Village,40.717010,-73.993530,Chinese Restaurant,4db3374590a0843f295fb69b
32,The Fat Radish,40.715323,-73.991950,English Restaurant,4c9d482e46978cfa8247967f

In [103]:
def getRestaurntDetails(names,IDs):
    
    details_list=[]
    for name,ID in zip(names,IDs):
        #print(name)
            
        # create the API request URL
        url="https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}".format(
            ID,
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION         )
            
        # make the GET request
        
        group_data = requests.get(url).json()
        
        #print(group_data)
         #break
        if group_data.get("response"):
        
            #print(group_data.get("response"))
        
            
            if group_data.get("response").get("venue"):
                if group_data.get("response").get("venue").get("price"):
                    if group_data.get("response").get("venue").get("price").get("message"):
                        
                            details_list.append([(name, 
                                                  group_data.get("response").get('venue').get("price").get("message"),
                                                  group_data.get("response").get('venue').get("rating"),
                                                  group_data.get("response").get('venue').get("likes").get("count")
                                                 ) ])
                            

    
    details = pd.DataFrame([item for detail_list in details_list for item in detail_list])
    #details.head()
    #print(details)
    details.columns = ['Rest_name', 
                       'Price', 
                       'Rating' ,
                       'Likes Count'
                      ]
    
    return(details)

In [104]:
nyc_rest_2.shape
nyc_rest_2_distinct=nyc_rest_2.drop_duplicates('Venue')
nyc_rest_3=nyc_rest_2_distinct.iloc[0:200,:]
nyc_rest_3

,Venue,Venue Latitude,Venue Longitude,Venue Category,Venue ID
6,Land & Sea Restaurant,40.877885,-73.905873,Seafood Restaurant,4b9c9c6af964a520b27236e3
12,Boston Market,40.877430,-73.905412,American Restaurant,585c205665e7c70a2f1055ea
25,Kiki's,40.714476,-73.992036,Greek Restaurant,5521c2ff498ebe2368634187
28,Spicy Village,40.717010,-73.993530,Chinese Restaurant,4db3374590a0843f295fb69b
32,The Fat Radish,40.715323,-73.991950,English Restaurant,4c9d482e46978cfa8247967f
...,...,...,...,...,...
637,Sumela Mediterranean Cafe & Grill,40.775117,-73.950642,Turkish Restaurant,598085d9ee628b12e387482a
641,Yummy Sushi,40.780214,-73.947012,Sushi Restaurant,4bce0d1129d4b71315dca7dc
645,The Writing Room,40.779401,-73.950698,New American Restaurant,52373a1411d27541297b921e
646,Noodle Fun,40.779795,-73.947454,Chinese Restaurant,536e6f06498eaee664b4938e
651,Hummus Kitchen,40.776372,-73.952828,Mediterranean Restaurant,4a355b56f964a520dc9c1fe3

<h2>Price, rating fand tips NYC</h2

In [110]:

nyc_rest_details = getRestaurntDetails(nyc_rest_3.get('Venue'),
                                       nyc_rest_3.get("Venue ID")
                                  )

nyc_rest_details.head(10)

ValueError: Length mismatch: Expected axis has 0 elements, new values have 4 elements

In [102]:
toronto_rest_details

,Rest_name,Price,Rating,Likes Count,Venue Latitude,Venue Longitude,Venue Category,Venue ID
0,Impact Kitchen,Moderate,8.7,51,43.656369,-79.356980,Restaurant,5612b1cc498e3dd742af0dc8
1,El Catrin,Expensive,8.2,465,43.650601,-79.358920,Mexican Restaurant,51ddecee498e1ffd34185d2f
2,Cocina Economica,Cheap,8.0,67,43.654959,-79.365657,Mexican Restaurant,5542ab36498e2f92a8c248f2
3,Cluny Bistro & Boulangerie,Very Expensive,8.3,182,43.650565,-79.357843,French Restaurant,53a22c92498ec91fda7ce133
4,Souvlaki Express,Moderate,7.6,7,43.655584,-79.364438,Greek Restaurant,4bc39c914cdfc9b6f29c9721
5,Archeo,Moderate,7.6,20,43.650667,-79.359431,Italian Restaurant,4ac3e6cef964a520629d20e3
6,Izumi,Moderate,7.5,17,43.649970,-79.360153,Asian Restaurant,50e88fc6e4b007fcbb57aae8
7,Flame Shack,Moderate,NaN,5,43.656844,-79.358917,Restaurant,51c085d3498eadedb67ba6cd
8,Mercatto,Expensive,8.3,55,43.660391,-79.387664,Italian Restaurant,4a8355bff964a520d3fa1fe3
9,Nando's,Moderate,8.1,179,43.661617,-79.386095,Portuguese Restaurant,52d884c5498ecf5c7cafe5ab
10,Sushi Box,Moderate,7.5,10,43.662960,-79.386580,Sushi Restaurant,4ecd63d96da162f1bb0f11c4
11,Como En Casa,Cheap,8.4,56,43.665160,-79.384796,Mexican Restaurant,4fb593c0e4b05a76e2ab2951
12,Tokyo Sushi,Moderate,8.0,33,43.665885,-79.386977,Sushi Restaurant,4afca145f964a5208e2422e3
13,The Captain's Boil,Expensive,7.5,39,43.662375,-79.383535,Seafood Restaurant,566387f1498e4003e174ef72
14,Hokkaido Ramen Santouka らーめん山頭火,Moderate,8.3,306,43.656435,-79.377586,Ramen Restaurant,509e9ef6e4b0ab175389a6c5
15,Salad King,Moderate,8.1,490,43.657601,-79.381620,Thai Restaurant,4ad4c061f964a52095f720e3
16,JOEY,Moderate,8.0,355,43.656094,-79.381878,American Restaurant,4df909dfe4cd2129701c0690
17,Crepe Delicious,Cheap,8.4,8,43.654536,-79.380889,Fast Food Restaurant,4e5d8181a8092f63968617ee
18,Chipotle Mexican Grill,Moderate,7.6,172,43.656860,-79.380910,Mexican Restaurant,4adc9148f964a520512d21e3
19,Spring Sushi,Moderate,7.6,193,43.656253,-79.380660,Sushi Restaurant,4fe4a773e4b0ef61f5212ecd
20,Kinka Izakaya Original,Moderate,8.7,386,43.660596,-79.378891,Japanese Restaurant,4b2bd898f964a52042bc24e3
21,Urban Herbivore,Moderate,8.0,47,43.654972,-79.380856,Vegetarian / Vegan Restaurant,4e5ff713ae60e9edf4ac0172
22,Milestones,Cheap,7.6,13,43.656308,-79.380822,Fast Food Restaurant,527dae3a498eaaa7f8fd063e
23,JOEY Eaton Centre,Moderate,8.0,8,43.655404,-79.381929,Restaurant,59246b5aad1789316b35d66c
24,Bourbon St. Grill,Cheap,7.7,11,43.655135,-79.380823,Fast Food Restaurant,4e8363c6e5fa5681e8c00e54
25,Paramount Fine Foods,Moderate,7.6,202,43.655029,-79.380245,Middle Eastern Restaurant,4c9cd4d37c096dcb9034c5d1
26,Kabul Express,Moderate,7.4,33,43.656691,-79.376643,Middle Eastern Restaurant,4adf8077f964a5202d7b21e3
27,Red Lobster,Moderate,8.1,136,43.656328,-79.383621,Seafood Restaurant,4ae3398ff964a520ed9121e3
28,Jack Astor's Bar & Grill,Moderate,7.3,264,43.656019,-79.380326,Restaurant,4ad9ffbbf964a520091d21e3
29,Ethiopiques,Moderate,7.3,21,43.656513,-79.377078,Ethiopian Restaurant,4c4e2474f53d0f47f18b13a6
30,Trattoria Mercatto,Moderate,7.8,106,43.654453,-79.380974,Italian Restaurant,4d306dd82748b60c62b6dba0
31,Scaddabush Italian Kitchen & Bar,Moderate,8.0,171,43.658920,-79.382891,Italian Restaurant,52f6816f11d24a43115dc834
32,Ali Baba's - Yonge north of Dundas,Moderate,7.4,8,43.657916,-79.381689,Middle Eastern Restaurant,568dcf20498e1601e2f8b87f
33,GB Hand-Pulled Noodles,Cheap,7.6,34,43.656434,-79.383783,Chinese Restaurant,58e91d60e0adac258fcea481
34,Fine Asian Bowl,Moderate,6.9,28,43.655387,-79.380326,Vietnamese Restaurant,4aea2b14f964a520ebb921e3
35,Gyu-Kaku Japanese BBQ,Moderate,8.7,42,43.651422,-79.375047,Japanese Restaurant,574ad72238fa943556d93b8e
36,Terroni,Expensive,8.6,275,43.650927,-79.375602,Italian Restaurant,4b49183ff964a520a46526e3
37,GEORGE Restaurant,Very Expensive,8.9,74,43.653346,-79.374445,Restaurant,4af618daf964a520220122e3
38,Mystic Muffin,Cheap,8.8,29,43.652484,-79.372655,Middle Eastern Restaurant,4b72f550f964a5202e922de3
39,The Carbon Bar,Expensive,8.1,142,43.653367,-79.374965,Restaurant,529e7344498e18bff5e60191
40,Richmond Station,Expensive,9.1,249,43.651569,-79.379266,American Restaurant,506db1a9e4b0a3f3b31412f0
41,NAMI,Expensive,8.0,55,43.650853,-79.375887,Japanese Restaurant,4b999927f964a5207c8635e3
42,Sukhothai,Moderate,8.6,217,43.648487,-79.374547,Thai Restaurant,50b7c53616485cd9efad60d5
43,La Bettola Di Terroni,Expensive,7.8,69,43.651993,-79.378056,Italian Restaurant,4c251062db519521621d2c3a
44,The Chase,Expensive,8.2,141,43.650952,-79.379422,New American Restaurant,5214e7c111d2a83379eae21f
45,Leña,Moderate,8.1,70,43.651722,-79.379205,Latin American Restaurant,57d0a3fb498e0fb29e892eed
46,Victoria's Restaurant,Moderate,7.8,6,43.649298,-79.376431,Restaurant,4ad4c05cf964a52006f620e3

In [115]:
nyc_rest_details

Empty DataFrame
Columns: []
Index: []